### ISSUE TITLE
Event cannot connect to redis due to empty password

### ISSUE THREAD

**Issue by netforce** [Resgrid/Core#144]
Docker deploy from resgrid/resgrid-setup.

'event' container seems to be missing a password in the RedisConnect string. 
Setting the Password value in the resgrid.env 'RESGRID__CacheConfig__RedisConnectionString' does not resolve this.

events-1    | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
events-1    | [INFO  wait] --------------------------------------------------------
events-1    | Resgrid.Config: Processing Environment Variables
events-1    | Resgrid.Config: Setting Value for System.String WorkerDbConnectionString
events-1    | Resgrid.Config: Setting Value for System.String PayloadKey
events-1    | Resgrid.Config: Setting Value for Int32 IngressProxyNetworkCidr
events-1    | Resgrid.Config: Setting Value for System.String IngressProxyNetwork
events-1    | Resgrid.Config: Setting Value for System.String ResgridEventingBaseUrl
events-1    | Resgrid.Config: Setting Value for System.String ResgridBaseUrl
events-1    | Resgrid.Config: Setting Value for System.String ResgridApiBaseUrl
events-1    | Resgrid.Config: Setting Value for Resgrid.Config.OutboundEmailTypes OutboundEmailType
api-1       | [INFO  wait] Host [events:80] not yet available...
events-1    | Resgrid.Config: Setting Value for System.String ExternalLinkUrlParamPassphrase
events-1    | Resgrid.Config: Setting Value for System.String ExternalAudioUrlParamPasshprase
events-1    | Resgrid.Config: Setting Value for Resgrid.Config.ErrorLoggerTypes ErrorLoggerType
events-1    | Resgrid.Config: Setting Value for Resgrid.Config.SystemEnvironment Environment
events-1    | Resgrid.Config: Setting Value for System.String RabbitUsername
events-1    | Resgrid.Config: Setting Value for System.String RabbitHostname
events-1    | Resgrid.Config: Setting Value for System.String RabbbitPassword
events-1    | Resgrid.Config: Setting Value for Int32 Port
events-1    | Resgrid.Config: Setting Value for System.String Host
events-1    | Resgrid.Config: Setting Value for System.String FromMail
events-1    | Resgrid.Config: Setting Value for Boolean EnableSsl
events-1    | Resgrid.Config: Setting Value for System.String SigningCert
events-1    | Resgrid.Config: Setting Value for System.String EncryptionCert
events-1    | Resgrid.Config: Setting Value for System.String ConnectionString
events-1    | Resgrid.Config: Setting Value for System.String LeafletTileUrl
events-1    | Resgrid.Config: Setting Value for System.String Environment
events-1    | Resgrid.Config: Setting Value for System.String ElkServiceUrl
events-1    | Resgrid.Config: Setting Value for System.String NoSqlConnectionString
events-1    | Resgrid.Config: Setting Value for System.String ConnectionString
events-1    | Resgrid.Config: Setting Value for System.String RedisConnectionString
web-1       | [INFO  wait] Host [api:80] not yet available...
api-1       | [INFO  wait] Host [events:80] not yet available...
web-1       | [INFO  wait] Host [api:80] not yet available...
events-1    | Unhandled exception. System.ArgumentException: The client secret cannot be null or empty. (Parameter 'secret')
events-1    |    at Microsoft.Extensions.DependencyInjection.OpenIddictValidationBuilder.SetClientSecret(String secret)
events-1    |    at Resgrid.Web.Eventing.Startup.<>c.<ConfigureServices>b__17_9(OpenIddictValidationBuilder options) in /src/Web/Resgrid.Web.Eventing/Startup.cs:line 239
events-1    |    at Microsoft.Extensions.DependencyInjection.OpenIddictValidationExtensions.AddValidation(OpenIddictBuilder builder, Action`1 configuration)
events-1    |    at Resgrid.Web.Eventing.Startup.ConfigureServices(IServiceCollection services) in /src/Web/Resgrid.Web.Eventing/Startup.cs:line 175
events-1    |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
events-1    |    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
events-1    |    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
events-1    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
events-1    |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
events-1    |    at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
events-1    |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
events-1    |    at Resgrid.Web.Eventing.Program.Main(String[] args) in /src/Web/Resgrid.Web.Eventing/Program.cs:line 13
api-1       | [INFO  wait] Host [events:80] not yet available...
web-1       | [INFO  wait] Host [api:80] not yet available...
events-1    | Aborted (core dumped)
api-1       | [INFO  wait] Host [events:80] not yet available...
web-1       | [INFO  wait] Host [api:80] not yet available...
web-1       | [INFO  wait] Host [api:80] not yet available...
events-1 exited with code 0

**Comment by ucswift** [comment]
@netforce thanks for reporting, I just merged a new setup docker compose today and updated the docs https://docs.resgrid.com/self-hosted/quick-start can you take a look and see if your still having issues.
